
//https://htmlcolors.com/color-mixer


export class DropdownArrays {

  static color = [
    '1) #ff0000  - red',
    '2) #ff0c00  - red orange',
    '3) #ff1700  - red orange',
    '4) #ff2300  - red orange',
    '5) #ff2e00  - red orange',
    '6) #ff3a00  - red orange',
    '7) #ff4500  - red orange',
    '8) #ff5100  - red orange',
    '9) #ff5c00  - red orange',
    '10) #ff6800 - red orange',
    '11) #ff7300 - red orange',
    '12) #ff7f00 - orange',
    '13) #ff8b00 - orange yellow',
    '14) #ff9600 - orange yellow',
    '15) #ffa200 - orange yellow',
    '16) #ffae00 - orange yellow',
    '17) #ffb900 - orange yellow',
    '18) #ffc500 - orange yellow',
    '19) #ffd000 - orange yellow',
    '20) #ffdc00 - orange yellow',
    '21) #ffe800 - orange yellow',
    '22) #fff300 - orange yellow',
    '23) #ffff00 - yellow',
    '24) #e8ff00 - yellow lime (green)',
    '25) #d1ff00 - yellow lime (green)',
    '26) #b9ff00 - yellow lime (green)',
    '27) #a2ff00 - yellow lime (green)',
    '28) #8bff00 - yellow lime (green)',
    '29) #74ff00 - yellow lime (green)',
    '30) #5dff00 - yellow lime (green)',
    '31) #46ff00 - yellow lime (green)',
    '32) #2eff00 - yellow lime (green)',
    '33) #17ff00 - yellow lime (green)',
    '34) #00ff00 - lime (green)',
    '35) #00ff17 - lime cyan (green)',
    '36) #00ff2e - lime cyan (green)',
    '37) #00ff46 - lime cyan (green)',
    '38) #00ff5d - lime cyan (green)',
    '39) #00ff74 - lime cyan (green)',
    '40) #00ff8b - lime cyan (green)',
    '41) #00ffa2 - lime cyan (green blue)',
    '42) #00ffb9 - lime cyan (green blue)',
    '43) #00ffd1 - lime cyan (green blue)',
    '44) #00ffe8 - lime cyan (green blue)',
    '45) #00ffff - cyan (blue)',
    '46) #00f3ff - cyan azure (blue)',
    '47) #00e8ff - cyan azure (blue)',
    '48) #00dcff - cyan azure (blue)',
    '49) #00d0ff - cyan azure (blue)',
    '50) #00c5ff - cyan azure (blue)',
    '51) #00b9ff - cyan azure (blue)',
    '52) #00aeff - cyan azure (blue)',
    '53) #00a2ff - cyan azure (blue)',
    '54) #0096ff - cyan azure (blue)',
    '55) #008bff - cyan azure (blue)',
    '56) #007fff - azure (blue)',
    '57) #0073ff - azure blue',
    '58) #0068ff - azure blue',
    '59) #005cff - azure blue',
    '60) #0051ff - azure blue',
    '61) #0045ff - azure blue',
    '62) #003aff - azure blue',
    '63) #002eff - azure blue',
    '64) #0023ff - azure blue',
    '65) #0017ff - azure blue',
    '66) #000cff - azure blue',
    '67) #0000ff - blue',
    '68) #0c00ff - blue violet',
    '69) #1700ff - blue violet',
    '70) #2300ff - blue violet',
    '71) #2e00ff - blue violet',
    '72) #3a00ff - blue violet',
    '73) #4500ff - blue violet',
    '74) #5100ff - blue violet',
    '75) #5c00ff - blue violet',
    '76) #6800ff - blue violet',
    '77) #7300ff - blue violet',
    '78) #7f00ff - violet',
    '79) #8b00ff - violet magenta (red)',
    '80) #9600ff - violet magenta (red)',
    '81) #a200ff - violet magenta (red)',
    '82) #ae00ff - violet magenta (red)',
    '83) #b900ff - violet magenta (red)',
    '84) #c500ff - violet magenta (red)',
    '85) #d000ff - violet magenta (red)',
    '86) #dc00ff - violet magenta (red)',
    '87) #e800ff - violet magenta (red)',
    '88) #f300ff - violet magenta (red)',
    '89) #ff00ff - magenta (red)',
    '90) #ff00f3 - magenta rose (red)',
    '91) #ff00e8 - magenta rose (red)',
    '92) #ff00dc - magenta rose (red)',
    '93) #ff00d0 - magenta rose (red)',
    '94) #ff00c5 - magenta rose (red)',
    '95) #ff00b9 - magenta rose (red)',
    '96) #ff00ae - magenta rose (red)',
    '97) #ff00a2 - magenta rose (red)',
    '98) #ff0096 - magenta rose (red)',
    '99) #ff008b - magenta rose (red)',
    '100) #ff007f - rose (red)',
    '101) #ff005f - magenta rose (red)',
    '102) #ff0040 - magenta rose (red)',
    '103) #ff0020 - magenta rose (red)'
  ];



  static saturation: string[] = [
    '1',
    '0.97',
    '0.93',
    '0.9',
    '0.8',
    '0.7',
    '0.6',
    '0.5',
    '0.4',
    '0.3',
    '0.2',
    '0.1',
    '0',
    '-0.1',
    '-0.2',
    '-0.3',
    '-0.4',
    '-0.5',
    '-0.6',
    '-0.7',
    '-0.8',
    '-0.9',
    '-0.92',
    '-0.94',
    '-0.96',
    '-0.98',
    '-1'];
  // https://stackoverflow.com/questions/45218663/use-workbench-colorcustomizations-in-extension

  static lightness: string[] = [
    '0',
    '-0.1',
    '-0.2',
    '-0.3',
    '-0.4',
    '-0.5',
    '-0.6',
    '-0.7',
    '-0.8',
    '-0.9',
    '-0.92',
    '-0.94',
    '-0.96',
    '-0.98',
    '-0.99',
    '2.0',
    '1.9',
    '1.8',
    '1.7',
    '1.6',
    '1.5',
    '1.4',
    '1.3',
    '1.2',
    '1.1',
    '1',
    '0.9',
    '0.8',
    '0.7',
    '0.6',
    '0.5',
    '0.4',
    '0.3',
    '0.2',
    '0.1',];


  static themes: string[] =
    [
      'Default Dark+',
      'Abyss',
      'Default Light+',
      'Visual Studio Dark',
      'Visual Studio Light',
      'Default High Contrast',
      'Kimbie Dark',
      'Monokai',
      'Monokai Dimmed',
      'Quiet Light',
      'Red',
      'Solarized Dark',
      'Solarized Light',
      'Tomorrow Night Blue'];


  static themeItems: string[] =
    ['contrastActiveBorder',
      'contrastBorder',
      'focusBorder',
      'foreground',
      'widget.shadow',
      'selection.background',
      'descriptionForeground',
      'errorForeground',
      'textBlockQuote.background',
      'textBlockQuote.border',
      'textCodeBlock.background',
      'textLink.activeForeground',
      'textLink.foreground',
      'textPreformat.foreground',
      'textSeparator.foreground',
      'button.background',
      'button.foreground',
      'button.hoverBackground',
      'dropdown.background',
      'dropdown.listBackground',
      'dropdown.border',
      'dropdown.foreground',
      'input.background',
      'input.border',
      'input.foreground',
      'input.placeholderForeground',
      'inputOption.activeBorder',
      'inputValidation.errorBackground',
      'inputValidation.errorForeground',
      'inputValidation.errorBorder',
      'inputValidation.infoBackground',
      'inputValidation.infoForeground',
      'inputValidation.infoBorder',
      'inputValidation.warningBackground',
      'inputValidation.warningForeground',
      'inputValidation.warningBorder',
      'scrollbar.shadow',
      'scrollbarSlider.activeBackground',
      'scrollbarSlider.background',
      'scrollbarSlider.hoverBackground',
      'badge.foreground',
      'badge.background',
      'progressBar.background',
      'list.activeSelectionBackground',
      'list.activeSelectionForeground',
      'list.dropBackground',
      'list.focusBackground',
      'list.focusForeground',
      'list.highlightForeground',
      'list.hoverBackground',
      'list.hoverForeground',
      'list.inactiveSelectionBackground',
      'list.inactiveSelectionForeground',
      'list.inactiveFocusBackground',
      'list.invalidItemForeground',
      'list.errorForeground',
      'list.warningForeground',
      'listFilterWidget.background',
      'listFilterWidget.outline',
      'listFilterWidget.noMatchesOutline',
      'activityBar.background',
      'activityBar.dropBackground',
      'activityBar.foreground',
      'activityBar.inactiveForeground',
      'activityBar.border',
      'activityBarBadge.background',
      'activityBarBadge.foreground',
      'sideBar.background',
      'sideBar.foreground',
      'sideBar.border',
      'sideBar.dropBackground',
      'sideBarTitle.foreground',
      'sideBarSectionHeader.background',
      'sideBarSectionHeader.foreground',
      'sideBarSectionHeader.border',
      'editorGroup.border',
      'editorGroup.dropBackground',
      'editorGroupHeader.noTabsBackground',
      'editorGroupHeader.tabsBackground',
      'editorGroupHeader.tabsBorder',
      'editorGroup.emptyBackground',
      'editorGroup.focusedEmptyBorder',
      'tab.activeBackground',
      'tab.activeForeground',
      'tab.border',
      'tab.activeBorder',
      'tab.unfocusedActiveBorder',
      'tab.activeBorderTop',
      'tab.unfocusedActiveBorderTop',
      'tab.inactiveBackground',
      'tab.inactiveForeground',
      'tab.unfocusedActiveForeground',
      'tab.unfocusedInactiveForeground',
      'tab.hoverBackground',
      'tab.unfocusedHoverBackground',
      'tab.hoverBorder',
      'tab.unfocusedHoverBorder',
      'tab.activeModifiedBorder',
      'tab.inactiveModifiedBorder',
      'tab.unfocusedActiveModifiedBorder',
      'tab.unfocusedInactiveModifiedBorder',
      'editorPane.background',
      'editor.background',
      'editor.foreground',
      'editorLineNumber.foreground',
      'editorLineNumber.activeForeground',
      'editorCursor.background',
      'editorCursor.foreground',
      'editor.selectionBackground',
      'editor.selectionForeground',
      'editor.inactiveSelectionBackground',
      'editor.selectionHighlightBackground',
      'editor.selectionHighlightBorder',
      'editor.wordHighlightBackground',
      'editor.wordHighlightBorder',
      'editor.wordHighlightStrongBackground',
      'editor.wordHighlightStrongBorder',
      'editor.findMatchBackground',
      'editor.findMatchHighlightBackground',
      'editor.findRangeHighlightBackground',
      'editor.findMatchBorder',
      'editor.findMatchHighlightBorder',
      'editor.findRangeHighlightBorder',
      'editor.hoverHighlightBackground',
      'editor.lineHighlightBackground',
      'editor.lineHighlightBorder',
      'editorLink.activeForeground',
      'editor.rangeHighlightBackground',
      'editor.rangeHighlightBorder',
      'editorWhitespace.foreground',
      'editorIndentGuide.background',
      'editorIndentGuide.activeBackground',
      'editorRuler.foreground',
      'editorCodeLens.foreground',
      'editorBracketMatch.background',
      'editorBracketMatch.border',
      'editorOverviewRuler.border',
      'editorOverviewRuler.findMatchForeground',
      'editorOverviewRuler.rangeHighlightForeground',
      'editorOverviewRuler.selectionHighlightForeground',
      'editorOverviewRuler.wordHighlightForeground',
      'editorOverviewRuler.wordHighlightStrongForeground',
      'editorOverviewRuler.modifiedForeground',
      'editorOverviewRuler.addedForeground',
      'editorOverviewRuler.deletedForeground',
      'editorOverviewRuler.errorForeground',
      'editorOverviewRuler.warningForeground',
      'editorOverviewRuler.infoForeground',
      'editorOverviewRuler.bracketMatchForeground',
      'editorError.foreground',
      'editorError.border',
      'editorWarning.foreground',
      'editorWarning.border',
      'editorInfo.foreground',
      'editorInfo.border',
      'editorHint.foreground',
      'editorHint.border',
      'editorUnnecessaryCode.border',
      'editorUnnecessaryCode.opacity',
      'editorGutter.background',
      'editorGutter.modifiedBackground',
      'editorGutter.addedBackground',
      'editorGutter.deletedBackground',
      'diffEditor.insertedTextBackground',
      'diffEditor.insertedTextBorder',
      'diffEditor.removedTextBackground',
      'diffEditor.removedTextBorder',
      'diffEditor.border',
      'editorWidget.background',
      'editorWidget.border',
      'editorWidget.resizeBorder',
      'editorSuggestWidget.background',
      'editorSuggestWidget.border',
      'editorSuggestWidget.foreground',
      'editorSuggestWidget.highlightForeground',
      'editorSuggestWidget.selectedBackground',
      'editorHoverWidget.background',
      'editorHoverWidget.border',
      'debugExceptionWidget.background',
      'debugExceptionWidget.border',
      'editorMarkerNavigation.background',
      'editorMarkerNavigationError.background',
      'editorMarkerNavigationWarning.background',
      'editorMarkerNavigationInfo.background',
      'peekView.border',
      'peekViewEditor.background',
      'peekViewEditorGutter.background',
      'peekViewEditor.matchHighlightBackground',
      'peekViewEditor.matchHighlightBorder',
      'peekViewResult.background',
      'peekViewResult.fileForeground',
      'peekViewResult.lineForeground',
      'peekViewResult.matchHighlightBackground',
      'peekViewResult.selectionBackground',
      'peekViewResult.selectionForeground',
      'peekViewTitle.background',
      'peekViewTitleDescription.foreground',
      'peekViewTitleLabel.foreground',
      'merge.currentHeaderBackground',
      'merge.currentContentBackground',
      'merge.incomingHeaderBackground',
      'merge.incomingContentBackground',
      'merge.border',
      'merge.commonContentBackground',
      'merge.commonHeaderBackground',
      'editorOverviewRuler.currentContentForeground',
      'editorOverviewRuler.incomingContentForeground',
      'editorOverviewRuler.commonContentForeground',
      'panel.background',
      'panel.border',
      'panel.dropBackground',
      'panelTitle.activeBorder',
      'panelTitle.activeForeground',
      'panelTitle.inactiveForeground',
      'statusBar.background',
      'statusBar.foreground',
      'statusBar.border',
      'statusBar.debuggingBackground',
      'statusBar.debuggingForeground',
      'statusBar.debuggingBorder',
      'statusBar.noFolderForeground',
      'statusBar.noFolderBackground',
      'statusBar.noFolderBorder',
      'statusBarItem.activeBackground',
      'statusBarItem.hoverBackground',
      'statusBarItem.prominentBackground',
      'statusBarItem.prominentHoverBackground',
      'titleBar.activeBackground',
      'titleBar.activeForeground',
      'titleBar.inactiveBackground',
      'titleBar.inactiveForeground',
      'titleBar.border',
      'menubar.selectionForeground',
      'menubar.selectionBackground',
      'menubar.selectionBorder',
      'menu.foreground',
      'menu.background',
      'menu.selectionForeground',
      'menu.selectionBackground',
      'menu.selectionBorder',
      'menu.separatorBackground',
      'notificationCenter.border',
      'notificationCenterHeader.foreground',
      'notificationCenterHeader.background',
      'notificationToast.border',
      'notifications.foreground',
      'notifications.background',
      'notifications.border',
      'notificationLink.foreground',
      'extensionButton.prominentForeground',
      'extensionButton.prominentBackground',
      'extensionButton.prominentHoverBackground',
      'pickerGroup.border',
      'pickerGroup.foreground',
      'terminal.background',
      'terminal.border',
      'terminal.foreground',
      'terminal.ansiBlack',
      'terminal.ansiBlue',
      'terminal.ansiBrightBlack',
      'terminal.ansiBrightBlue',
      'terminal.ansiBrightCyan',
      'terminal.ansiBrightGreen',
      'terminal.ansiBrightMagenta',
      'terminal.ansiBrightRed',
      'terminal.ansiBrightWhite',
      'terminal.ansiBrightYellow',
      'terminal.ansiCyan',
      'terminal.ansiGreen',
      'terminal.ansiMagenta',
      'terminal.ansiRed',
      'terminal.ansiWhite',
      'terminal.ansiYellow',
      'terminal.selectionBackground',
      'terminalCursor.background',
      'terminalCursor.foreground',
      'debugToolBar.background',
      'debugToolBar.border',
      'editor.stackFrameHighlightBackground',
      'editor.focusedStackFrameHighlightBackground',
      'welcomePage.background',
      'welcomePage.buttonBackground',
      'welcomePage.buttonHoverBackground',
      'walkThrough.embeddedEditorBackground',
      'gitDecoration.addedResourceForeground',
      'gitDecoration.modifiedResourceForeground',
      'gitDecoration.deletedResourceForeground',
      'gitDecoration.untrackedResourceForeground',
      'gitDecoration.ignoredResourceForeground',
      'gitDecoration.conflictingResourceForeground',
      'gitDecoration.submoduleResourceForeground',
      'settings.headerForeground',
      'settings.modifiedItemIndicator',
      'settings.dropdownBackground',
      'settings.dropdownForeground',
      'settings.dropdownBorder',
      'settings.dropdownListBorder',
      'settings.checkboxBackground',
      'settings.checkboxForeground',
      'settings.checkboxBorder',
      'settings.textInputBackground',
      'settings.textInputForeground',
      'settings.textInputBorder',
      'settings.numberInputBackground',
      'settings.numberInputForeground',
      'settings.numberInputBorder',
      'breadcrumb.foreground',
      'breadcrumb.background',
      'breadcrumb.focusForeground',
      'breadcrumb.activeSelectionForeground',
      'breadcrumbPicker.background',
      'editor.snippetTabstopHighlightBackground',
      'editor.snippetTabstopHighlightBorder',
      'editor.snippetFinalTabstopHighlightBackground',
      'editor.snippetFinalTabstopHighlightBorder'];


}